# Change these first
owner: bywhite0 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://zh.wikipedia.org
  - name: Wodemo主站
    url: https://bywhite.wodemo.net
    icon: https://q1.qlogo.cn/g?b=qq&nk=3240558932&s=640&t=1
  - name: GitHub分站
    url: https://bywhite0.github.io
    icon: https://q1.qlogo.cn/g?b=qq&nk=3240558932&s=640&t=1
  - name: Vercel镜像站
    url: https://bywhite.vercel.app
    icon: https://bywhite0.github.io/heads/icon-apple.jpg
  - name: Status状态页
    url: https://bywhite0.github.io/status
    icon: https://bywhite0.github.io/status/logo-512.png
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  faviconSvg: https://cdn.jsdelivr.net/gh/bywhite0/status@master/assets/upptime-icon.svg
  name: 网站状态
  introTitle: "网站状态监测"
  introMessage: 实时更新 | [**我也要整一个！**](https://github.com/upptime/upptime)
  navbar:
    - title: 状态
      href: /
    - title: 首页
      href: /status
    - title: 在GitHub查看
      href: https://github.com/$OWNER/$REPO

commitMessages:
  readmeContent: ":pencil: 在README.md更新摘要 [skip ci] [upptime]"
  summaryJson: ":card_file_box: 更新状态 [skip ci] [upptime]"
  #statusChange: "$EMOJI $SITE_NAME 状态为 $STATUS ($RESPONSE_CODE) 响应时长:$RESPONSE_TIMEms) [skip ci] [upptime]"
  graphsUpdate: ":bento: 更新图表 [skip ci] [upptime]"
  

i18n: 
  activeIncidents: 已激活的事件
  allSystemsOperational: 系统运行正常。
  incidentReport: "事件记录 #$NUMBER →"
  activeIncidentSummary: 激活于 $DATE （共 $POSTS 条回复）
  incidentTitle: 事件 $NUMBER 详情
  incidentDetails: 事件详情
  incidentFixed: 已修复
  incidentOngoing: 进行中
  incidentOpenedAt: 激活于
  incidentClosedAt: 关闭于
  incidentSubscribe: 订阅更新
  incidentViewOnGitHub: 在GitHub上查看
  incidentCommentSummary: $AUTHOR 回复于 $DATE
  incidentBack: ← 返回
  pastIncidents: 以前的事件
  pastIncidentsResolved: 于$MINUTES分钟后解决（共 $POSTS 条回复）
  liveStatus: 实时状态
  overallUptime: "连通率: $UPTIME"
  overallUptimeTitle: 连通率
  averageResponseTime: "平均响应时长: $TIMEms"
  averageResponseTimeTitle: 响应时长
  sevelDayResponseTime: 一周响应时长
  responseTimeMs: 响应时长 (ms)
  #up: :white_check_mark:正常
  #down: :warning:异常
  #degraded: 超时
  loading: Loading
  navGitHub: GitHub
  footer: Powered by [Upptime](https://upptime.js.org) with GitHub Actions, Issues, and Pages.
  rateLimitExceededTitle: "&#x26a0;&#xfe0f;超过限制"
  rateLimitExceededIntro: "您已经超过了一小时内可以处理的请求数量，因此您必须等待，然后才能再次访问此网站。或者，您可以添加一个GitHub个人访问令牌来继续使用该网站。"
  rateLimitExceededWhatDoesErrorMean: 为什么？
  rateLimitExceededErrorMeaning: 本网站使用GitHub API来访问网站状态的实时数据。默认情况下，GitHub允许每个IP每小时请求60次，您已达到限制。
  rateLimitExceededErrorHowCanFix: 我该如何解决？
  rateLimitExceededErrorFix: 您可以等待一个小时使恢复限制。或者，您也可以添加您的GitHub个人访问令牌，这将允许您每小时请求5000次。
  rateLimitExceededGeneratePAT: 了解如何添加个人访问令牌
  rateLimitExceededHasSet: 您已设置个人访问令牌
  rateLimitExceededRemoveToken: 移除令牌
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: 粘贴你的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 出错了
  errorIntro: 获取服务器状态信息失败
  errorText: 你可以过几分钟再试一下
  errorHome: 回到主页
  pastScheduledMaintenance: 维护完成
  scheduledMaintenance: 计划维护
  scheduledMaintenanceSummaryStarted: 从 $DATE 开始执行并持续了 $DURATION 分钟
  scheduledMaintenanceSummaryStarts: 从 $DATE 开始执行并持续了 $DURATION 分钟
  startedAt: 开始于
  startsAt: 开始于
  duration: 响应时间
  durationMin: $DURATION 分钟
  incidentCompleted: 成功
  incidentScheduled: 等待中
  url: "URL"
  status: "状态"
  history: "历史"
  up: "🟩正常"
  degraded: "🟨超时"
  down: "🟥异常"
  responseTimeGraphAlt: "响应时间图表"
  ms: "ms"
  responseTime: "响应时间"
  responseTimeDay: "日均响应时间"
  responseTimeWeek: "周均响应时间"
  responseTimeMonth: "月均响应时间"
  responseTimeYear: "年均响应时间"
  uptime: "连通率"
  uptimeDay: "日均连通率"
  uptimeWeek: "周均连通率"
  uptimeMonth: "月均连通率"
  uptimeYear: "年均联通率"
  #liveStatus: "在线统计"
  liveStatusHtmlComment: "<!--在线统计-->"
  #allSystemsOperational: "🟩系统运行正常"
  degradedPerformance: "🟨响应超时"
  completeOutage: "🟥系统异常"
  partialOutage: "🟧部分异常"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
